apiVersion: v1
kind: Service
metadata:
  name: score-service
spec:
  selector:
    {{- include "scoreService.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.scoreService.service.port }}
      targetPort: {{ .Values.scoreService.deployment.containerPort }}
