apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.teamService.service.name}}
spec:
  selector:
    {{- include "teamService.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.teamService.service.port }}
      targetPort: {{ .Values.teamService.deployment.containerPort }}
