apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: score-service
  template:
    metadata:
      labels:
        app: score-service
    spec:
      containers:
      - name: score-service
        image: score-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: score-service
spec:
  selector:
    app: score-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
      - name: player-service
        image: player-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  selector:
    app: player-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web
