apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.scoreService.service.name}}
spec:
  selector:
    {{- include "scoreService.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.scoreService.service.port }}
      portName: {{ .Values.scoreService.service.portName }} 
      targetPort: {{ .Values.scoreService.deployment.containerPort }}
