apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamService.serviceName" . }}
spec:
  selector:
    {{- include "teamService.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.teamService.service.port }}
      name: {{ .Values.teamService.service.portName }}
      targetPort: {{ .Values.teamService.deployment.containerPort }}
