apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  selector:
    {{- include "playerService.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.playerService.service.port }}
      targetPort: {{ .Values.playerService.deployment.containerPort }}
