apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.playerService.service.name}}
spec:
  selector:
    {{- include "playerService.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.playerService.service.port }}
      portName: {{ .Values.playerService.service.portName }} 
      targetPort: {{ .Values.playerService.deployment.containerPort }}
