apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    {{- include "frontend.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.deployment.containerPort }}
