apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "scoreService.serviceName" . }}-destination-rule
spec:
  host: {{ include "scoreService.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - labels:
      version: stable
    name: stable
