run-all:
	echo "building all the images all at once"
	
	# cd frontend-blazor && bash run-script.sh
	cd player-service && bash run-script.sh
	cd score-service && bash run-script.sh
	cd team-service && bash run-script.sh

run-player:
	cd player-service && bash run-script.sh

run-team:
	cd team-service && bash run-script.sh

run-score:
	cd score-service && bash run-script.sh
