name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # You can change this to match the branch you want to trigger the workflow
    
  workflow_dispatch: # This event allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: setup-buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    - id: login-dockerhub
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - id: copy-data-folder
      name: Copy data folder to player and score service folders
      run: |
        cp -r data player-service/
        cp -r data score-service/

    - id: dockerx-build-and-push-ps
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: player-service
        tags: gat786/cric-player-service:latest
    
    - id: dockerx-build-and-push-ss
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: score-service
        tags: gat786/cric-score-service:latest
        # platforms: linux/arm64
